name: Publish to GitHub npm registry

on:
  push:
    # branches: [master] 
    tags:
      - '*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - run: corepack enable
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
        registry-url: https://npm.pkg.github.com/
    # - name: Authentication
    #   run: |
    #     echo npmAuthToken: "$NODE_AUTH_TOKEN" >> ./.yarnrc.yml
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn workspaces focus --all --production
    # - run: yarn npm publish
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
